[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["unser229"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
scikit-learn = "*"
imbalanced-learn = "*"
matplotlib = "*"
seaborn = "*"
joblib = "*"
telethon = "^1.36.0"
telebot = "^0.0.5"
schedule = "^1.2.2"
snscrape = "^0.7.0.20230622"
pyrogram = "^2.0.106"
tgcrypto = "^1.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "Main:main"
