[tool.poetry]
name = "blackfox"
version = "0.1.0"
description = ""
authors = ["unser229 <gycogco@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.2"
tensorrt = "^10.6.0.post1"
optuna = "^4.1.0"
tensorflow = {extras = ["and-cuda"], version = "^2.18.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
