@startuml
skinparam componentStyle uml2
skinparam nodesep 20
skinparam ranksep 30

left to right direction

rectangle "Клиентские приложения" {
  [Веб-интерфейс] as WebUI
  [Мобильное приложение] as MobileApp
  [API клиенты] as APIClients
}


rectangle "Сервер" as Server{
  rectangle "main.py" {
    component "API Gateway" as Gateway {
    [FastAPI] as FastAPI
    }

    package "Сервис классификации" {
      [API FastAPI] as FastAPI
      [Text Classifier] as TextClassifier
      [Image Classifier] as ImageClassifier
      [Health Check] as HealthCheck
    }
  }
  rectangle "Listen.py" {
    [tdlib] as tdlib
    database "advertisments.csv"
    database "regular.csv"
  }

  package "Модели машинного обучения" {
    [Text Model] as TextModel
    [Image Model] as ImageModel
    [Vectorizer] as TextVectorizer
  }
}

rectangle "Домашний пк для разработки" as Home {
  package "Learn" {
    [torch_text.py] as Torch_text
    [resnet_slut_detector.py] as resnet_slut_detector
  }
  package "Server_run"{
    [main.py] as main
    [listen.py] as listen
  }
  package "Data" {
    database "slut"
    database "regular"
    database "add.json"
    database "posts.json"
  }
  package "Model" {
    [random_forest model ] as random_forest_model
    [torch_text model] as torch_text_model
    [resnet_model] as resnet_model
  }
  [Chrome extension] as chrome
}

rectangle "Внешние сервисы " {
  [Telegram] as Telegram
}

tdlib --> Telegram

Home --> Server : ssh

FastAPI --> TextClassifier : Текстовая классификация
FastAPI --> ImageClassifier : Классификация изображений

TextClassifier --> TextModel : Загружает модель
TextClassifier --> TextVectorizer : Использует для векторизации
ImageClassifier --> ImageModel : Загружает модель

WebUI --> Gateway
MobileApp --> Gateway
APIClients --> Gateway

@enduml